import datetime
from const import material_property as mp
from const import const_local_mesh as clm
from const import const_global_mesh as cgm

# Analysis mode
static_mode = False  # Set to True for static analysis (via --static_only flag)

# Sneddon data source selection
# Choose which Sneddon integral data file to use:
#   'mathematica': Use sneddon_SA.mat (generated by Mathematica, reference)
#   'python':      Use sneddon_python.mat (generated by Python/scipy)
sneddon_data_source = 'python'  # Options: 'mathematica' or 'python'

# Crack geometry (from param.txt)
# Default values for dynamic mode
c = 4.0e-3  # Crack radius [m]
thi = 1.0  # Thickness [m]

# Crack velocity (from param.txt)
V = 700.0  # Velocity [m/s]

# Step control
step_start = 0  # stepini
step_end = 101  # stepend (-1 means calculate from c/hL)
REstart = 0  # 1: restart from dynamic analysis (set to 0 if stepini==0)

# Calculate stepall
if step_end == -1:
    stepall = round(c / clm.hL)
else:
    stepall = step_end

# Boundary condition type
nbcebc = 1  # 0: nodal force, 1: essential boundary condition

# Domain size for global mesh (dynamic mode defaults)
lGoutxy = 2 * c
lGoutz = c
WidthG = 8.0e-3  # [m]
HeightG = 4.0e-3  # [m]

# Calculate global element size (dynamic mode defaults)
import numpy as np
# hG = cgm.mu_G * clm.hL * cgm.rGL
# nPtsX = int(np.ceil(WidthG / hG))
# nPtsY = nPtsX
# nPtsZ = int(np.ceil(HeightG / hG))
Lx = WidthG * cgm.mu_G  # Adjusted domain length in X direction
Ly = WidthG * cgm.mu_G  # Adjusted domain length in Y direction
Lz = HeightG * cgm.mu_G  # Adjusted domain length in Z direction

nPtsX = int(np.ceil(Lx / (clm.hL * cgm.rGL))) + cgm.p
nPtsY = nPtsX
nPtsZ = int(np.ceil(Lz / (clm.hL * cgm.rGL))) + cgm.r

nofix = 1  # Changing boundary conditions: 0=No, 1=Yes

# # J integral
# Rj0 = 1.5
# Rj1 = 1.51
# Wj0 = 0.5
# Wj1 = 0.51

# HHT-alpha method
# hs_iga reads Alpha from input.dat and computes:
#   Beta = (1 - Alpha)^2 / 4, Gamma = 0.5 - Alpha
Alpha = -0.02
Beta = (1.0 - Alpha) ** 2 / 4.0
Gamma = 0.5 - Alpha
# Default blended mass-lumping factor used by hs_iga for dynamic analyses.
# This is distinct from the HHT-alpha parameter above. Explicit SFEM environment
# variables may override it for dedicated mass-lumping studies.
SFEM_MASS_LUMPING_ALPHA = 0.02

# integral point
ngp = 2

nrefLlist = 1  # href=2^nref
inc = 1  # num. of increment (basically 1)

# Nu = 0.35   # Poisson's ratio
# ee = 3.2e9  # Young's modulus [Pa]
# Rho = 1170. # density [m/s^2]

# Rayleigh damping - mass coefficient
Alpha_l = 0.

# Beta_l (Rk) is calculated dynamically in input_generator.py using:
# Beta_l = 2.57 * h * sqrt(rho/E)
# where h = hG (global) or hL (local) depending on islocal flag

OPENMP = 24      # number of openmp thread


TEST_NUMBER_LIST = [4]
TEST_NUMBER = TEST_NUMBER_LIST[0]
INC_LIST = [1]
DIR_NAME_ADD_LIST = ["R0.8_No.1", "R0.8_No.2", "R1.0_No.1", "R1.0_No.2", "R1.2_No.1", "R1.2_No.2"]
DIR_NAME_ADD = DIR_NAME_ADD_LIST[TEST_NUMBER-1]
DIR_NAME_TEST_LIST = ["R0_8__NO1", "R0_8__NO2", "R1_0__NO1", "R1_0__NO2", "R1_2__NO1", "R1_2__NO2"]
DIR_NAME_TEST = "Test"
# DAY = datetime.datetime.now().strftime("%Y-%m-%d")
DAY = "test"

LOCAL_01_LIST = [1]
Local01 = LOCAL_01_LIST[0]
DYNAMIC_01_LIST = [1]
HREF_LIST = [3]
HREF = HREF_LIST[0]
NFR_LIST = [1]

TEST_START = 1
TEST_END = 1
GET_CTOD = 0

UBUNTU_DIR = "PMMA_old"


DOS_OPEN = 2    # dos screen 0: Not open　1:Open and close　2:Keeping open

ABO = 0  # 1:abort just before calculation of solver
USER_NAME = "lab"
REPO_NAME = "hs_iga"

# STEP_TIME = 1.2915155311516764e-6

OUTPUT_FOLDER = "outputfolder"
CALC_STEP = 1
# JOB_NAME = "step_" + str(STEP_START) + "_exp_" + str(CALC_STEP)
# FOLDER_NAME = JOB_NAME

is_cross = False
isgetctod = False


def update_for_static_mode():
    """Update simulation parameters for static mode
    
    Static mode uses dimensionless (normalized) units, completely independent from dynamic mode.
    This is an idealized case where all quantities are pure numbers without physical units.
    
    IMPORTANT: This function must be called AFTER clm.update_for_static_mode()
               to ensure hL is updated before calculating nPtsX/Y/Z.
    """
    global c, WidthG, HeightG, Lx, Ly, Lz, nPtsX, nPtsY, nPtsZ
    import numpy as np
    
    # Re-import to get updated values after clm.update_for_static_mode() was called
    from const import const_local_mesh as clm_updated
    from const import const_global_mesh as cgm_updated
    
    # Static mode: dimensionless/normalized units (matching Mathematica)
    c = 1.0       # Normalized crack radius (dimensionless)
    WidthG = 2.0  # Normalized domain width (dimensionless)
    HeightG = 1.0 # Normalized domain height (dimensionless)
    
    # Calculate adjusted domain lengths
    Lx = WidthG * cgm_updated.mu_G  # Adjusted domain length in X direction
    Ly = WidthG * cgm_updated.mu_G  # Adjusted domain length in Y direction
    Lz = HeightG * cgm_updated.mu_G  # Adjusted domain length in Z direction

    # Calculate number of control points using UPDATED hL value
    nPtsX = int(np.ceil(Lx / (clm_updated.hL * cgm_updated.rGL))) + cgm_updated.p
    nPtsY = nPtsX
    nPtsZ = int(np.ceil(Lz / (clm_updated.hL * cgm_updated.rGL))) + cgm_updated.r
    # Recalculate mesh parameters
    # hG_bf = cgm.mu_G * clm.hL * cgm.rGL
    # nPtsX = int(np.ceil(WidthG / hG_bf)) + 1
    # nPtsY = nPtsX
    # nPtsZ = int(np.ceil(HeightG / hG_bf)) + 1
    
    # Calculate actual element sizes
    # hGX = cgm.mu_G * WidthG / (nPtsX - 1)
    # hGY = cgm.mu_G * WidthG / (nPtsY - 1)
    # hGZ = cgm.mu_G * HeightG / (nPtsZ - 1)
    # hG = hG_bf
